In [1]:
# import tensorflow 

import tensorflow as tf
import numpy as np

In [2]:
# 0으로 된 텐서 생성

tf.zeros(2)

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>

In [8]:
# tensorflow는 텐서 그 자체의 값이 아닌 텐서의 참조를 반환한다.
# 텐서  값을 반환하려면 tf.Tensor.eval 사용

a = tf.zeros(2)
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 0.], dtype=float32)>>

In [12]:
# tf.zeros & tf.ones 이용하여 다양한 크기의 텐서 생성 및 확인

a = tf.zeros((2,3))
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>>

In [11]:
b = tf.ones((2,2,2))
b.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>>

In [13]:
# 0 or 1 제외한 다른 값으로 텐서를 채우려면 tf.fill() 이용

b = tf.fill((2,2),value=5.)
b.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[5., 5.],
       [5., 5.]], dtype=float32)>>

In [16]:
# tf.constant는 tf.fill과 유사한 함수, 프로그램 실행 중에 변경할 수 없는 텐서를 생성

a = tf.constant(3)
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(), dtype=int32, numpy=3>>

In [29]:
# 정규분포로 텐서 추출

a = tf.random.normal((2,2), mean=0, stddev=1)
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.50980496, -0.9425625 ],
       [-1.1269273 , -0.94159013]], dtype=float32)>>

In [30]:
# tf.random.normal() 보다는 tf.truncated.normal()을 흔히 사용(절단정규분포)
# 평균에서 표준편차의 2 배 이상 나는 값은 모두 제외하고 다시 추출하는 방식
# tf.random.uniform() 또한 tf.random.normal()과 유사, 지정한 범위에 걸친 균등분포에서 난수를 추출한다는 점이 다르다.

a = tf.random.uniform((2,2),minval=-2, maxval=2)
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 0.6179166, -1.3021736],
       [-1.6626949,  0.2216425]], dtype=float32)>>

In [31]:
# tensorflow는 python 연산자를 오버로딩해 표준 파이썬 연산자를 기본적인 텐서 연산에 사용할 수 있게 만들었다.

c = tf.ones((2,2))
d = tf.ones((2,2))
e = c + d
e.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 2.],
       [2., 2.]], dtype=float32)>>

In [32]:
f = 2 * e
f.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[4., 4.],
       [4., 4.]], dtype=float32)>>

In [33]:
c = tf.fill((2,2),2.)
d = tf.fill((2,2),7.)
e = c * d
e.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 14.],
       [14., 14.]], dtype=float32)>>

In [34]:
# tf.eye()를 사용하여 원하는 크기의 단위행렬을 생성할 수 있다.

a = tf.eye(4)
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>>

In [39]:
# tf.range(start, limit, delta)
# tf.linalg.diag(diagonal)을 이용하여 대각행렬 생성할 수 있다.

r = tf.range(1, 5, 1)
r.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>>

In [40]:
d = tf.linalg.diag(r)
d.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])>>

In [41]:
# 전치행렬, 행렬을 전치하려면 tf.transpose()로 처리 가능하다.

a = tf.ones((2,3))
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>>

In [43]:
at = tf.transpose(a)
at.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>>

In [44]:
# 행렬곱 수행

a = tf.ones((2,3))
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>>

In [45]:
b = tf.ones((3,4))
b.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>>

In [46]:
c = tf.matmul(a,b)
c.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[3., 3., 3., 3.],
       [3., 3., 3., 3.]], dtype=float32)>>

In [50]:
# 다양한 형의 텐서 생성

a = tf.ones((2,2), dtype=tf.int32)
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>>

In [54]:
b = tf.cast(a, tf.float32)
b.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>>

In [55]:
# 텐서 형상 조작

a = tf.ones(8)
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(8,), dtype=float32, numpy=array([1., 1., 1., 1., 1., 1., 1., 1.], dtype=float32)>>

In [56]:
b = tf.reshape(a, (4,2))
b.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>>

In [57]:
c = tf.reshape(a, (2,2,2))
c.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2, 2), dtype=float32, numpy=
array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]], dtype=float32)>>

In [62]:
a = tf.ones(2)
a.get_shape()

TensorShape([2])

In [63]:
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>>

In [65]:
b = tf.expand_dims(a, 0)
b.get_shape()

TensorShape([1, 2])

In [66]:
b.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[1., 1.]], dtype=float32)>>

In [67]:
c = tf.expand_dims(a, 1)
c.get_shape()

TensorShape([2, 1])

In [68]:
c.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[1.],
       [1.]], dtype=float32)>>

In [69]:
d = tf.squeeze(b)
d.get_shape()

TensorShape([2])

In [70]:
d.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2,), dtype=float32, numpy=array([1., 1.], dtype=float32)>>

In [71]:
# 브로드캐스팅(broadcastiong)은 텐서 시스템에서 행렬과 다른 크기의 벡터를 서로 더할 때 쓰이는 용어이다.

a = tf.ones((2,2))
a.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.]], dtype=float32)>>

In [72]:
b = tf.range(0,2,1, dtype=tf.float32)
b.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2,), dtype=float32, numpy=array([0., 1.], dtype=float32)>>

In [73]:
c = a + b
c.eval

<bound method _EagerTensorBase.eval of <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [1., 2.]], dtype=float32)>>